### PR TITLE
Fix suborchestrator input double serialization issue

### LINKED ISSUE #436: Double quotes added to input passed from suborchestrator to activity
**Describe the bug**
If input is passed from an orchestration -> suborchestration -> activity function, there are extra double quotes added to the input. There seems to be some extra layer of serialization/deserialization happening here.

**Investigative information**

- Durable Functions extension version: 2.9.0
- durable-functions npm module version: 2.1.1
- Language (JavaScript/TypeScript) and version: TypeScript
- Node.js version: 16.13.0

**To Reproduce**

1. Create a simple orchestration that calls a suborchestration with some input, which in turn calls an activity function with the same input. Here, I am using the `SayHelloWithSubOrchestration` orchestration example in the samples:

`SayHelloWithSubOrchestration/index.js`:

```JS
const df = require("durable-functions");

module.exports = df.orchestrator(function* (context) {
    const input = context.df.getInput();

    const output = yield context.df.callSubOrchestrator("SayHelloWithActivity", input);
    return output;
});
```

`SayHelloWithActivity/index.js`:

```JS
const df = require("durable-functions");

module.exports = df.orchestrator(function* (context) {
    const input = context.df.getInput();

    const output = yield context.df.callActivity("Hello", input);
    return output;
});
```

`Hello/index.js`:

```JS
module.exports = function (context) {
    return `Hello ${context.bindings.name}!`;
};
```

2. Call the `SayHelloWithSubOrchestrator` orchestration with some input. If running locally, make the following HTTP request:

```http
POST http://localhost:7071/api/orchestrators/SayHelloWithSubOrchestrator

"Cairo"
```

**Expected behavior**
Output of the orchestration should be: `"Hello Cairo!"`

**Actual behavior**
Output of the orchestration instead is: `"Hello \"Cairo\"!"` with extra double quotes around the input.

### PR DESCRIPTION
**Pull request by hossam-nasr**
Fixes #436

### CODE REVIEW

**Comment by davidmrdavid** [comment]
@hossam-nasr: wouldn't this also affect the suborchestrator with-retry API? And what about entities?

**Comment by hossam-nasr** [comment]
@davidmrdavid Good call out! I tested the issue with `context.df.callSubOrchestratorWithRetry()` and `context.df.callEntity()` and found that it does reproduce, so I introduced the fix to the `CallSubOrchestratorWithRetryAction` and `CallEntityAction` too

**Review by davidmrdavid — APPROVED** [review]
LGTM

@hossam-nasr: can you please test signalEntity as well and apply the same fix if appropiate? GIven that the fix is just a 1 liner, don't worry about re-requesting my approval if you add it to this PR

**Comment by hossam-nasr** [comment]
@davidmrdavid SignalEntity doesn't seem to exist on `v3.x` 🤨 I think I branched `v3.x` out of `v2.x` before the `signalEntity()` addition was made. I will test this tho when I add it to this branch too, and I'll introduce the fix if it's required.

**Pull request merged**
