### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by hossam-nasr**

### CODE REVIEW

**Review by ejizba — APPROVED** [review]

**Review by davidmrdavid — APPROVED** [review]
LGTM!

**Comment by davidmrdavid** [comment]
@hossam-nasr: please **squash-and-merge** :)

**Comment by davidmrdavid** [comment]
and delete branch :P

**Comment by ejizba** [comment]
@davidmrdavid fyi you can change the repo settings for both of those. There's a setting to allow only "squash and merge" for a PR and a setting that auto-deletes PR branches after they're merged

**Comment by davidmrdavid** [comment]
Thanks for the heads up @ejizba, that sounds like a great idea. I'll look into setting that

**Pull request merged**
